name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.5
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: '>=2.12.3 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ">=1.7.1 <3.0.0"
  collection: ^1.15.0
  gherkin: ^2.0.5+1
  source_gen: ^1.1.0
  build: ^2.1.0
  glob: ^2.0.1
  # gherkin:
    # path: ../dart_gherkin

dev_dependencies:
  meta: ^1.7.0 
  pedantic: ^1.11.1
  build_config: ^1.0.0

flutter:
