name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 1.1.8+6
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  glob: ^1.1.7
  meta: ">=1.1.6 <2.0.0"
  gherkin: ^1.1.8+3
  # gherkin:
    # path: ../dart_gherkin

dev_dependencies:
  test:
  pedantic:

flutter:
