name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 1.0.9
author: Jon Samwell <jonsamwell@gmail.com>
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  glob: ^1.1.7
  meta: ">=1.1.6 <=1.1.7"
  gherkin: ^1.0.7

dev_dependencies:
  test: ">=1.6.1 <=1.6.4"

flutter:
