name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 1.2.0
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ">=0.37.0 <0.41.0"
  glob: ^1.1.7
  meta: ">=1.1.6 <2.0.0"
  source_gen: ^0.9.10+1
  build: ^1.6.0
  build_config: ^0.4.5
  integration_test: ^1.0.1
  # gherkin: ^1.1.9
  # gherkin:
    # path: ../dart_gherkin
  gherkin:
    git:
      url: https://github.com/jonsamwell/dart_gherkin.git
      ref: 6db02b6553200ea498c24315dc18373a6682fe7d
      # ref: code_gen_changes

dev_dependencies:
  test:
  pedantic: ^1.9.2

flutter:
