name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 2.0.0-nullsafety.0
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  glob: ^2.0.0
  meta: ">=1.1.6 <2.0.0"
  gherkin: ^2.0.0-nullsafety.0
  # gherkin:
  #   path: ../dart_gherkin

dev_dependencies:
  test:
  pedantic: ^1.9.2

flutter:
