name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.17
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: '>=2.1.0 < 6.0.0'
  collection: ^1.15.0
  gherkin: ^3.1.0
  source_gen: ^1.1.1
  build: ^2.1.1
  glob: ^2.0.2

dev_dependencies:
  meta: '>=1.7.0 < 2.0.0'
  pedantic: ^1.11.1
  build_config: ^1.0.0
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.16.0

flutter:
